### ISSUE TITLE
Can not find path to android/ios projects in monorepo

### ISSUE THREAD

**Issue by hebadarweesh1** [alexandermendes/semantic-release-react-native#6]
Having a monoRepo project and trying to change the versions in build.gradle and Info.plist but it can not find the files is there a property similar to pkgRoot found in semantic-release ?

[3:52:37 PM] [semantic-release] [semantic-release-react-native] › ℹ  Versioning Android
[3:52:37 PM] [semantic-release] [semantic-release-react-native] › ✘  No file found at /home/runner/work/client-apps/client-apps/android/app/build.gradle
[3:52:37 PM] [semantic-release] [semantic-release-react-native] › ℹ  Versioning iOS
[3:52:37 PM] [semantic-release] [semantic-release-react-native] › ✘  No Xcode project file found at /home/runner/work/client-apps/client-apps/ios

My configuration file is 
const config = {
  branches: ['master'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [ '@semantic-release/npm', {
        npmPublish: false,
        pkgRoot: 'my-app-directory',
      },],
    [
      'semantic-release-react-native', { pkgRoot: 'my-app-directory', },],
    [ '@semantic-release/git',
      {
        assets: [
          'my-app-directory/package.json',
          'my-app-directory/ios/**/Info.plist',
          'my-app-directory/android/app/build.gradle',
        ],
        message:
          'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      }, ],
    '@semantic-release/github', ],};
module.exports = config;

**Comment by alexandermendes** [comment]
Well there's an `androidPath` and an `iosPath` that might work for you, see the readme:

https://github.com/alexandermendes/semantic-release-react-native#configuration

**Comment by hebadarweesh1** [comment]
### Directory Hierarchy
<img width="339" alt="image" src="https://github.com/alexandermendes/semantic-release-react-native/assets/121934385/51ca54f0-f8f5-4b98-8392-7c3214816ad1">

### Configuration file
const config = {
  branches: ['branch-name'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/npm',
      {
        npmPublish: false,
        // Specify the path to the app's directory
        pkgRoot: 'apps/current-app'
      }
    ],
    [
      'semantic-release-react-native',
      {
        androidPath: 'apps/current-app/android/app/build.gradle',
        iosPath: 'apps/current-app/ios'
      }
    ],
    [
      '@semantic-release/git',
      {
        assets: [
          'apps/current-app/package.json',
          'apps/current-app/ios/**/Info.plist',
          'apps/current-app/ios/**/*.pbxproj',
          'apps/current-app/android/app/build.gradle'
        ],
        message:
          'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
      }
    ],
    '@semantic-release/github'
  ]
};
module.exports = config;

### Github error while running CI workflow

[1:18:50 PM] [semantic-release] [semantic-release-react-native] › ℹ  Versioning iOS
[1:18:50 PM] [semantic-release] › ✘  Failed step "prepare" of plugin "semantic-release-react-native"
[1:18:50 PM] [semantic-release] › ✘  An error occurred while running semantic-release: peg$SyntaxError: Expected "\"", "\\'", "\\\"", "\\n", or [^\\"] but "\\" found.
    at peg$buildStructuredError (/home/runner/work/client-apps/client-apps/node_modules/pbxproj-dom/parser.js:318:12)
    at Object.peg$parse [as parse] (/home/runner/work/client-apps/client-apps/node_modules/pbxproj-dom/parser.js:921:11)
    at Xcode.open (/home/runner/work/client-apps/client-apps/node_modules/pbxproj-dom/xcode.js:16:43)
    at versionIos (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/version/ios.js:244:31)
    at /home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:77:34
    at step (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:33:23)
    at Object.next (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:14:53)
    at /home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:4:12) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: true,
      ignoreCase: false
    },
    { type: 'literal', text: '\\"', ignoreCase: false },
    { type: 'literal', text: "\\'", ignoreCase: false },
    { type: 'literal', text: '\\n', ignoreCase: false },
    { type: 'literal', text: '"', ignoreCase: false }
  ],
  found: '\\',
  location: {
    start: { offset: 31316, line: 467, column: 71 },
    end: { offset: 31317, line: 467, column: 72 }
  },
  pluginName: 'semantic-release-react-native'
}
peg$SyntaxError: Expected "\"", "\\'", "\\\"", "\\n", or [^\\"] but "\\" found.
    at peg$buildStructuredError (/home/runner/work/client-apps/client-apps/node_modules/pbxproj-dom/parser.js:318:12)
    at Object.peg$parse [as parse] (/home/runner/work/client-apps/client-apps/node_modules/pbxproj-dom/parser.js:921:11)
    at Xcode.open (/home/runner/work/client-apps/client-apps/node_modules/pbxproj-dom/xcode.js:16:43)
    at versionIos (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/version/ios.js:244:31)
    at /home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:77:34
    at step (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:33:23)
    at Object.next (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:14:53)
    at /home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/client-apps/client-apps/node_modules/semantic-release-react-native/dist/prepare.js:4:12) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: true,
      ignoreCase: false
    },
    { type: 'literal', text: '\\"', ignoreCase: false },
    { type: 'literal', text: "\\'", ignoreCase: false },
    { type: 'literal', text: '\\n', ignoreCase: false },
    { type: 'literal', text: '"', ignoreCase: false }
  ],
  found: '\\',
  location: {
    start: { offset: 3[131](https://github.com/thndrapp/client-apps/actions/runs/7005562522/job/19055559730#step:6:132)6, line: 467, column: 71 },
    end: { offset: 31317, line: 467, column: 72 }
  },
  pluginName: 'semantic-release-react-native'
}
Error: Process completed with exit code 1.

**Comment by alexandermendes** [comment]
If you look at the error it seems it doesn't like something about your pbxproj file. Not entirely sure what, will be coming from https://github.com/NativeScript/pbxproj-dom somewhere

**Comment by chriswickham** [comment]
I'm also experiencing this issue with the following config:

```
const config = {
  "branches": ['main'],
  "tagFormat": "${version}",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "semantic-release-react-native",
    ['@semantic-release/changelog', { changeLogFile: 'CHANGELOG.md' }],
    [
      "@semantic-release/git",
      {
        "assets": [
          'CHANGELOG.md',
          'package.json',
          "ios/**/Info.plist",
          "android/app/build.gradle",
        ],
        message: 'chore(release): ${nextRelease.version}\n\n${nextRelease.notes}',
      },
    ],
  ]
}

module.exports = config;
```

**Comment by alexandermendes** [comment]
I expect this is fixed in https://github.com/alexandermendes/semantic-release-react-native/releases/tag/v1.8.3

**Comment by alexandermendes** [comment]
In fact it didn't, however I'll cover any future updates in https://github.com/alexandermendes/semantic-release-react-native/issues/7, as the original issue in this one was sorted
